pub mod binance;
pub mod cast;
pub mod coingecko;
pub mod crypto_provider;
pub mod gnews;
pub mod history;
pub mod openweathermap;
pub mod ota;
pub mod server;
pub mod spotify;
pub mod stock_provider;
pub mod weather_provider;
pub mod yahoo_finance;

pub use crypto_provider::CryptoProvider;
pub use gnews::GNewsProvider;
pub use history::{PriceHistory, Timeframe};
pub use server::run_server;
pub use stock_provider::StockProvider;
pub use weather_provider::{DayForecast, WeatherProvider};
